---
title: "Classification"
output: pdf_document
date: "2023-03-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

## Part 1: Executive Summary

## Part 2: Technical Summary

### Problem description

initial data summary

```{r}
#df <- readr::read_csv("https://www.louisaslett.com/Courses/MISCADA/hotels.csv")
#View(df)
```



```{r}
df <- read.csv("https://www.louisaslett.com/Courses/MISCADA/hotels.csv", na.strings=c("NA", "NULL"))

dim(df)
summary(df)
```






```{r}
unique(df$hotel)
unique(df$is_canceled)
```

```{r}
table(df$reservation_status)
table(df$is_canceled)
```

```{r}
table(df$country)
```
```{r}
apply(is.na(df), 2, sum)
```

```{r}
#df <- read.csv("https://www.louisaslett.com/Courses/MISCADA/hotels.csv", na.strings=c("NA", "NULL"))
dim(df)
summary(df)
str(df)
apply(is.na(df), 2, sum)
df <- df[, c("is_canceled", "hotel", "lead_time", "arrival_date_year", "arrival_date_month",
             "arrival_date_week_number", "arrival_date_day_of_month", "stays_in_weekend_nights",
             "stays_in_week_nights", "adults", "children", "babies", "meal", "distribution_channel",
             "is_repeated_guest", "previous_cancellations", "previous_bookings_not_canceled", 
             "reserved_room_type", "assigned_room_type", "booking_changes", "deposit_type",
             "days_in_waiting_list", "customer_type", "adr", "required_car_parking_spaces",
             "total_of_special_requests")]
df$is_canceled <- factor(df$is_canceled)
```

```{r}
library("tidyverse")
library(ggplot2)
ggplot(df,
       aes(x = adr, y = stays_in_weekend_nights+stays_in_week_nights)) +
  geom_point()
```

```{r}
ggplot(df |>
         filter(adr < 4000) |> 
         mutate(total_nights = stays_in_weekend_nights+stays_in_week_nights),
       aes(x = adr, y = total_nights)) +
  geom_point(alpha=0.1)
```


```{r}
df <- df |>
  filter(adr < 4000) |> 
  mutate(total_nights = stays_in_weekend_nights+stays_in_week_nights)
```




```{r}
ggplot(df,
       aes(x = adr, y = total_nights)) +
  geom_bin2d(binwidth=c(10,1)) +
  geom_smooth()
```










```{r}


library(ggplot2)
barplot(table(df$arrival_date_month))
barplot(table(df$is_canceled, df$hotel))
```


```{r}
ggplot(df, aes(x = is_canceled, fill = hotel)) +
  geom_bar(stat = "count", position = "fill")
```


```{r}
ggplot(df, aes(x = is_canceled, fill = assigned_room_type)) +
  geom_bar(stat = "count", position = "fill")
```


```{r}
ggplot(df, aes(x = is_canceled, fill = factor(arrival_date_year))) +
  geom_bar(stat = "count", position = "fill")
```


```{r}
ggplot(df, aes(x = is_canceled, fill = factor(previous_cancellations))) +
  geom_bar(stat = "count", position = "fill")
```


```{r}
ggplot(df, aes(x = is_canceled, y = lead_time)) +
  geom_boxplot()
```

```{r}
ggplot(df, aes(x = is_canceled, y = stays_in_week_nights)) +
  geom_boxplot()

```

data processing:

```{r}
df$arrival_date_year <- as.factor(df$arrival_date_year)
df$children <- as.integer(df$children)
df$is_repeated_guest <- as.factor(df$is_repeated_guest)

df <- df[-which(df$adr < 0| df$adr>1000),]
df <- na.omit(df)
```

variable selection:

```{r}
df_mod <- as.data.frame(model.matrix(~.-1, df)[, -1])
log_mod1 <- glm(is_canceled1~., data = df_mod, family = binomial)
summary(log_mod1)
```

```{r}
log_mod2 <- update(log_mod1, .~.-assigned_room_typeB - assigned_room_typeC -
                     assigned_room_typeD - assigned_room_typeE - assigned_room_typeF -
                     assigned_room_typeG - assigned_room_typeH - assigned_room_typeI - 
                     assigned_room_typeK - assigned_room_typeL - assigned_room_typeP - 
                     required_car_parking_spaces - babies)
summary(log_mod2)
```

```{r}
df2 <- df[, -c(19, 12,  25)]
df_mod2 <- as.data.frame(model.matrix(~.-1, df2)[, -1])
names(df_mod2) <- make.names(names(df_mod2))
```

model fitting:

```{r}
prop.table(table(df2$is_canceled))  # base model, naive model
```

```{r}
set.seed(123)
df_mod2$is_canceled1 <- as.factor(df_mod2$is_canceled1)
df_mod2 <- df_mod2[sample(nrow(df_mod2)),]
ind <- round(nrow(df_mod2) * 0.7)
df_train <- df_mod2[1:ind,]
df_test <- df_mod2[-(1:ind),]
```

logistic regression:

```{r}
mod1 <- glm(is_canceled1~., data = df_train, family = binomial)
train_pred <- ifelse(predict(mod1, df_train, type = "response") > 0.5, 1, 0)
mean(train_pred == df_train$is_canceled1)

test_pred <- ifelse(predict(mod1, df_test, type = "response") > 0.5, 1, 0)
mean(test_pred == df_test$is_canceled1)
```

knn:

```{r}
library(FNN)

train_pred <- knn(df_train[, -1], df_train[, -1], df_train$is_canceled1, k = 1)
mean(train_pred == df_train$is_canceled1)
test_pred <- knn(df_train[, -1], df_test[, -1], df_train$is_canceled1, k = 1)
mean(test_pred == df_test$is_canceled1)

train_pred <- knn(df_train[, -1], df_train[, -1], df_train$is_canceled1, k = 10)
mean(train_pred == df_train$is_canceled1)
test_pred <- knn(df_train[, -1], df_test[, -1], df_train$is_canceled1, k = 10)
mean(test_pred == df_test$is_canceled1)


train_pred <- knn(df_train[, -1], df_train[, -1], df_train$is_canceled1, k = 20)
mean(train_pred == df_train$is_canceled1)
test_pred <- knn(df_train[, -1], df_test[, -1], df_train$is_canceled1, k = 20)
mean(test_pred == df_test$is_canceled1)
```

```{r}
#ctrl <- trainControl(method = "cv", number = 5)

#tuneGrid <- expand.grid(k = 1:20, distance = c("euclidean", "manhattan", "maximum"))

#knnFit <- train(is_canceled1~., data = df_train, method = "knn", trControl = ctrl, tuneLength = 10, tuneGrid = tuneGrid)

```





```{r}
train_pred <- knn(df_train[, -1], df_train[, -1], df_train$is_canceled1, k = 25)
mean(train_pred == df_train$is_canceled1)

test_pred <- knn(df_train[, -1], df_test[, -1], df_train$is_canceled1, k = 25)
mean(test_pred == df_test$is_canceled1)
```

lda:

```{r}
library(MASS)

lda1 <- lda(is_canceled1~., data = df_train)
train_pred <- predict(lda1, df_train)$class
mean(train_pred == df_train$is_canceled1)
test_pred <- predict(lda1, df_test)$class
mean(test_pred == df_test$is_canceled1)
```

decision tree

```{r}
library(rpart)

tree1 <- rpart(is_canceled1~., data = df_train)
summary(tree1)
```

```{r}
library(rpart.plot)
prp(tree1)
```

```{r}

train_pred <- predict(tree1, newdata = df_train, type = "class")
mean(train_pred == df_train$is_canceled1)
test_pred <- predict(tree1, newdata = df_test, type = "class")
mean(test_pred == df_test$is_canceled1)
```

random forest

```{r}
#install.packages("randomForest")
library(randomForest)

rf <- randomForest(is_canceled1~., data = df_train)

train_pred <- predict(rf, newdata = df_train)
mean(train_pred == df_train$is_canceled1)
test_pred <- predict(rf, newdata = df_test)
mean(test_pred == df_test$is_canceled1)
```

```{r}
varImpPlot(rf)
importance(rf)
```

```{r}
view(df_train)
str(df_train)
```


```{r}
bestmtry <- tuneRF(df_train[, c("lead_time", "hotelResort.Hotel",
                                "arrival_date_year2016","arrival_date_year2017",
                                "arrival_date_monthAugust","arrival_date_monthDecember","arrival_date_monthFebruary",
                                "arrival_date_monthJanuary","arrival_date_monthJuly","arrival_date_monthJune",
                                "arrival_date_monthMarch","arrival_date_monthMay","arrival_date_monthNovember",
                                "arrival_date_monthOctober","arrival_date_monthSeptember","arrival_date_week_number",
                                "arrival_date_day_of_month","stays_in_weekend_nights","stays_in_week_nights",
                                "adults","children","mealFB","mealHB","mealHB","mealSC","mealUndefined",
                                "distribution_channelDirect","distribution_channelGDS","distribution_channelTA.TO",
                                "distribution_channelUndefined","is_repeated_guest1",
                                "previous_cancellations", "previous_bookings_not_canceled",
                                "reserved_room_typeB","reserved_room_typeC","reserved_room_typeD","reserved_room_typeE",
                                "reserved_room_typeF","reserved_room_typeG","reserved_room_typeH","reserved_room_typeL",
                                "reserved_room_typeP","booking_changes","deposit_typeNon.Refund","deposit_typeRefundable",
                                "days_in_waiting_list","customer_typeGroup","customer_typeTransient","customer_typeTransient.Party",
                                "total_of_special_requests","total_nights",
                                "adr")], 
                   df_train$is_canceled1, stepFactor=1.5, improve=1e-5, ntree=200)

print(bestmtry)
```

```{r}
tuneRF(df_train[, c("lead_time", "hotelResort.Hotel",
                                "arrival_date_year2016","arrival_date_year2017",
                                "arrival_date_monthAugust","arrival_date_monthDecember","arrival_date_monthFebruary",
                                "arrival_date_monthJanuary","arrival_date_monthJuly","arrival_date_monthJune",
                                "arrival_date_monthMarch","arrival_date_monthMay","arrival_date_monthNovember",
                                "arrival_date_monthOctober","arrival_date_monthSeptember","arrival_date_week_number",
                                "arrival_date_day_of_month","stays_in_weekend_nights","stays_in_week_nights",
                                "adults","children","mealFB","mealHB","mealHB","mealSC","mealUndefined",
                                "distribution_channelDirect","distribution_channelGDS","distribution_channelTA.TO",
                                "distribution_channelUndefined","is_repeated_guest1",
                                "previous_cancellations", "previous_bookings_not_canceled",
                                "reserved_room_typeB","reserved_room_typeC","reserved_room_typeD","reserved_room_typeE",
                                "reserved_room_typeF","reserved_room_typeG","reserved_room_typeH","reserved_room_typeL",
                                "reserved_room_typeP","booking_changes","deposit_typeNon.Refund","deposit_typeRefundable",
                                "days_in_waiting_list","customer_typeGroup","customer_typeTransient","customer_typeTransient.Party",
                                "total_of_special_requests","total_nights",
                                "adr")], df_train$is_canceled1, ntreeTry = 200, stepFactor = 1.5, plot = TRUE)
```



```{r}
rf <- randomForest(is_canceled1~., data = df_train, mtry = bestmtry[which.min(bestmtry[,2]), 1])

train_pred <- predict(rf, newdata = df_train)
mean(train_pred == df_train$is_canceled1)
test_pred <- predict(rf, newdata = df_test)
mean(test_pred == df_test$is_canceled1)
```

model evaluation

```{r}
#install.packages("caret")
library(caret)

confusionMatrix(df_test$is_canceled1, test_pred, positive = "1")
```
